POST http://localhost:8000/api/forgot-password
Content-Type: application/json
Accept: application/json
//Authorization: Bearer 4|ySMWmOUYcHNRVPlmOG1BIzwlk6eZWoiOYLeXSdNTca5a02a4

{
    "email": "moh@gmail.com"
}