POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json
//Authorization: Bearer 1|seo0t1HRGneDdogOlos3x6W9xJkIzxT6ZixkpRBN393afb81

{
    "name": "mohamed",
    "email": "moh@gmail.com",
    "password": "password",
    "password_confirmation": "password"
}