POST http://localhost:8000/api/reset-password
Content-type: application/json
Accept: application/json
//Authorization: Bearer 4|ySMWmOUYcHNRVPlmOG1BIzwlk6eZWoiOYLeXSdNTca5a02a4

{
    "token" : "b5d87b893d591f0ca3207a5b6affb0acccd947e6b0fac4d6c16efa24fab3e4eb",
    "email": "moh@gmail.com",
    "password": "password_2",
    "password_confirmation": "password_2"
}